# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Feel++ Book
email: christophe.prudhomme@feelpp.org
description: > # this means to ignore newlines until "baseurl:"
  This is the Feel++ Book
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: feelpp
github_username:  prudhomm

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-cayman

assets:
  sources:
    - _assets/fonts

plugins:
  - jekyll-feed
  - jekyll-asciidoc

include:
  - docs/man/README.adoc

exclude:
  - Gemfile
  - Gemfile.lock
  - "0*"
  - vendor
  - "math/*.tex"
  - math/fem/auto/
  - "math/*.adoc"
  - "math/*.html"
  - math/auto
  - book.html
  - book.pdf
  - /auto/
  - docs/man/0*
  - docs/man/l*

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - allow-uri-read=true
    - idseparator=_
    - source-highlighter=pygments
    - pygments-style=manni
    - pyggments-css=class
    - pygments-linenums-mode=inline
    - icons=font
    - imagesdir=/images
